### ISSUE TITLE
Differences between agabani/tor-operator

### ISSUE THREAD

**Issue by samip5** [bugfest/tor-controller#73]
I think it could be useful to have some comparision.

First result I found wasn't this controller, but rather https://github.com/agabani/tor-operator

**Comment by bugfest** [comment]
Hi @samip5, thanks for letting me know. I wasn't aware of this project; I guess it is shown as first result because it has been more recently updated. Not sure what's the motivation other than using rust; I would have prefer to agree on a common Tor spec and then have operators implementing it. I must say there are some nice features there like HPA and OpenTelemetry.

What kind of comparison are you looking for?

**Comment by samip5** [comment]
Something like feature parity, but it seems that the other one for one runs tor as root..
